### ISSUE TITLE
check column names

### ISSUE THREAD

**Issue by yoid2000** [diffix/coronaVirus#5]
@sebastian please look at the `colInfo.json` file and see if you want to change any column names.

The column names are labeled `manColName`.

The question has the label `phrase`.

Feel free to change any as you wish. I have no strong preferences.

**Comment by sebastian** [comment]
I am a little concerned about the sample values in the `colInfo`-file? It seems these values could be things that wouldn't necessarily pass our anonymization? And as such shouldn't be part of this repo either. At least if I understand it correctly these are user provided free form replies?

Here are examples:
- https://github.com/diffix/coronaVirus/blob/master/cov-clear/scripts/colInfo.json#L772-L782
- https://github.com/diffix/coronaVirus/blob/master/cov-clear/scripts/colInfo.json#L263-L274

**Comment by sebastian** [comment]
Since I have so few suggestions for improvements I'll add them here:

- https://github.com/diffix/coronaVirus/blob/master/cov-clear/scripts/colInfo.json#L422: `are_you` -> `gender`
- https://github.com/diffix/coronaVirus/blob/master/cov-clear/scripts/colInfo.json#L768: `post` -> `postal_code` or `zipcode`?

**Comment by sebastian** [comment]
Removed personal data, and updated column names.
Force pushed changes.
